name: C++ CI Serial Programs Mac Intel
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/cpp-ci-serial-programs-base.yml
    with:
      os: macos-15-intel
      compiler: default